version: '3.8'

services:
  # s3:
  #   image: minio/minio
  #   container_name: mlflow_minio
  #   ports:
  #     - "9000:9000" # API port
  #     - "9001:9001" # Console UI port
  #   environment:
  #     - MINIO_ROOT_USER=admin
  #     - MINIO_ROOT_PASSWORD=password
  #   command: server /data --console-address ":9001"
  #  store raw ingestion data
  #  mlflow uses by "--default-artifact-root s3://mlflow-bucket/" in mlflow service's command

  # postgres:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_DB: mlflow
  #     POSTGRES_USER: mlflow
  #     POSTGRES_PASSWORD: mlflow
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   use by  "--backend-store-uri ${DB_URI}" in mlflow service's command
  
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: mlflow_server
    # depends_on:
    #   - postgres
    #   - s3
    ports:
      - "5000:5000"
    # environment:
    #   - DB_URI=postgresql://mlflow:mlflow@db:5432/mlflow
    volumes:
      - ./artifacts:/mlflow/artifacts
    networks:
      - sa-network
    command: >
      mlflow server 
      --backend-store-uri sqlite:///mlflow/mlflow.db
      --default-artifact-root /mlflow/artifacts
      --host 0.0.0.0 
      --port 5000


  
  # redis:
  #   image: redis:6-alpine
  #   ports:
  #     - "6379:6379"
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8000:8000"
    depends_on:
      - mlflow
      # - s3
      # - redis
    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      REDIS_URL: redis://redis:6379
    volumes:
      - ./models:/app/models
      # - ./logs:/app/logs
      - ./artifacts:/app/artifacts
    networks:
      - sa-network
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus  
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    networks:
      - sa-network
    depends_on:
      - app
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - sa-network
    depends_on:
      - prometheus

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - sa-network
    depends_on:
      - mlflow
      - app
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "2.0"
    #       memory: 500mb

# volumes:
#   postgres_data:

networks:
  sa-network:
    driver: bridge