events {}

http {
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=5r/s;

    upstream mlflow {
        server mlflow:5000;
    }

    upstream api {
        server app:8000;
    }

    server {
        listen 80;
        # pass the original host header from the client to the backend
        proxy_set_header Host $host;
        # pass the real client IP address
        proxy_set_header X-Real-IP $remote_addr;

        # MLflow UI
        location /mlflow/ {
            proxy_pass http://mlflow/;  
        }

        # API inference
        location /api/ {
            proxy_pass http://app/;

            # apply rate limiting, allow 10 extra requests in a burst without delay
            limit_req zone=api_limit burst=10 nodelay;

            # 
            # proxy_read_timeout 300;
            # proxy_connect_timeout 300;
            # proxy_send_timeout 300;
        }

        # deny access .file
        location ~ /\. {
            deny all;
        }
    }
}