events {}

http {

    upstream mlflow {
        server mlflow:5000;
    }

    upstream api {
        server api:8000;
    }

    server {
        listen 80;

        # MLflow UI
        location /mlflow/ {
            proxy_pass http://mlflow/;
        }

        # API inference
        location /api/ {
            proxy_pass http://api/;
        }
    }
}